Prevent the changelist causing an exception
When the the context processor for inserting `request` into the Context is not present in TEMPLATE_CONTEXT_PROCESSORS, `{% result_tree ... %}` will fail because `request` will resolve to `''` and then will end up doing `AttributeError: 'str' object has no attribute 'path'`